### ISSUE TITLE
Image copy-paste for web version

### ISSUE THREAD

**Issue by malivinayak** [OutdatedGuy/Whats-That-Anime#14]
For web version consider this feature as just copy pasting the image. 

Explanation - when we take screenshot from anime it will automatically copied to our clipboard. after that just for sec of searching we need to save it and again upload it for result. Instead of saving and uploading, it is really good if we can directly paste it into website after taking a screenshot. 
For live demo [check this](https://www.remove.bg/) out. You can either copy the image either by pressing key ```ctrl + C``` (for windows ) { or by right click to image and copy} or just take a screenshot as ```🪟windows + shift + s``` and paste it by keys ```ctrl + V```  to this [website](https://www.remove.bg/)

Take a look for [reference ](https://stackoverflow.com/questions/68145566/flutter-web-image-copy-and-paste) about this feature.
Hope it will make scenes for web version.

**Comment by OutdatedGuy** [comment]
Yo @malivinayak, thanks for filling this feature request.

Copy and Paste is a nice idea for web version. However, due to **Web Clipboard API** limitations, Flutter as of now does not support accessing image data from the **Clipboard** in the web platform.

Hence, this issue is currently being put on hold. If you manage to find a way, feel free to send a PR.

**Comment by malivinayak** [comment]
Thank You for your reply. If I manage to implement I will definitely let you know.
